services:
  - type: web
    name: subhashacademy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PGSSLMODE
        value: require
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_SECURE_COOKIE
        value: "1"
